REM gun data for stock firearms
insert into system.guns (serial, manufacturer, model, caliber, location) values ('MIODI64LMA', 'GLOCK', 'MODEL 43', '9MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('BIBZU1D0ZG', 'GLOCK', 'MODEL 43', '9MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('PDLJJLRW22', 'GLOCK', 'MODEL 22', '.40SW', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('JBI30OIJ27', 'GLOCK', 'MODEL 22', '.40SW', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('FN4K8O6U62', 'GLOCK', 'MODEL 22', '.40SW', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('JU88BWEJX7', 'GLOCK', 'MODEL 27', '.40SW', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('DN8PR3JBN4', 'GLOCK', 'MODEL 27', '.40SW', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('RZZHDHF65O', 'GLOCK', 'MODEL 27', '.40SW', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('MPEJ3B4Q6M', 'GLOCK', 'MODEL 19', '9MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('TU6BB1LPR9', 'GLOCK', 'MODEL 19', '9MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('LRPDB5RKXH', 'GLOCK', 'MODEL 21', '.45 ACP', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('YXXYIOB0V8', 'GLOCK', 'MODEL 21', '.45 ACP', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('OL03II5BFV', 'SPRINGFIELD ARMORY', '1911 MILL-SPEC', '.45 ACP', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('ALNHZ2DG23', 'SPRINGFIELD ARMORY', 'XD MOD.2', '9MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('ZH1Y2I0MOI', 'SPRINGFIELD ARMORY', 'XD(M) COMPACT', '.40SW', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('VZT0JIJVBS', 'SPRINGFIELD ARMORY', 'XD(M) COMPACT', '9MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('OZA1QG9Q72', 'SPRINGFIELD ARMORY', 'XD(M)', '.45 ACP', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('AX4NYZIL9M', 'SPRINGFIELD ARMORY', 'SAINT', 'NATO 5.56/.223', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('DVZA57LYEP', 'SPRINGFIELD ARMORY', 'SAINT', 'NATO 5.56/.223', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('AJUK2NJK9E', 'BARRETT', 'MODEL 95', '', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('XV62F603Q6', 'BARRETT', 'MODEL 98B', '', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('VV33190V9X', 'COLT', 'O1091', '.45 ACP', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('VDQIUF4E0R', 'COLT', 'O1091', '.45 ACP', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('ICXKFO2M4C', 'COLT', 'M4A1 CARBINE', 'NATO 5.56/.223', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('UDKSBW1GJL', 'COLT', 'AR15A4', 'NATO 5.56/.223', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('GP90126CMQ', 'RUGER', 'LCP', '.380 ACP', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('FRIK37XHP5', 'RUGER', 'LCR', '.22LR', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('HZ9ME3UU1B', 'RUGER', 'LCRX', '.357 MAGNUM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('GYZD4YG5UD', 'RUGER', '10/22', '.22LR', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('RWHG99U6QE', 'RUGER', '10/22', '.22LR', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('IMOAUEHOOP', 'RUGER', 'MINI-14 TACTICAL', '.300 BLACKOUT', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('NQZCSPMV8E', 'KEL-TEC', 'KSG', '12 GAUGE', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('YD941TMQXM', 'KEL-TEC', 'KSG', '12 GAUGE', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('QY9JLSOZAL', 'KEL-TEC', 'KSG', '12 GAUGE', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('RRF63D40V3', 'MOSSBERG', '500 TACTICAL', '12 GAUGE', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('ZQ5LEJLXLE', 'MOSSBERG', '500 TACTICAL', '12 GAUGE', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('ZW9PPMPSTU', 'MOSSBERG', '500 TACTICAL', '12 GAUGE', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('BYOOUHAR3T', 'MOSSBERG', '500 TACTICAL', '12 GAUGE', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('XH5VK8VDVS', 'SMITH AND WESSON', 'MODEL 340 PD', '.357 MAGNUM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('TOLI3E3WUV', 'SMITH AND WESSON', 'MODEL 340 PD', '.357 MAGNUM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('VQ03W885RJ', 'SMITH AND WESSON', 'MODEL 340 PD', '.357 MAGNUM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('YDTPKMZ2VC', 'SMITH AND WESSON', 'MODEL 340 PD', '.357 MAGNUM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('BQBDFR3FSR', 'SMITH AND WESSON', 'MODEL 340 PD', '.357 MAGNUM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('ZITJH1WMEL', 'SMITH AND WESSON', 'MODEL SW500', '.500 MAGNUM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('SEEROA4DNE', 'SMITH AND WESSON', 'MODEL SW500', '.500 MAGNUM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('PZEORQDEZU', 'SMITH AND WESSON', 'MODEL GOVERNOR', '.45 ACP', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('RTG08NK2G1', 'SMITH AND WESSON', 'MODEL GOVERNOR', '.45 ACP', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('BC3E6JC822', 'SMITH AND WESSON', 'MODEL GOVERNOR', '.45 ACP', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('POBNTFYF22', 'SMITH AND WESSON', 'MP .380 BODYGUARD', '.380 ACP', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('RW4Q3DANFS', 'SMITH AND WESSON', 'MP .380 BODYGUARD', '.380 ACP', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('LUTK4UJBX0', 'SMITH AND WESSON', 'MP SHIELD', '.40SW', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('IW3TUSPKQ7', 'SMITH AND WESSON', 'MP SHIELD', '.40SW', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('RHMBF2ZEP0', 'SMITH AND WESSON', 'MP SHIELD', '.40SW', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('RZHRVWV812', 'BERETTA', 'MODEL 92', '9MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('DWGC232JC4', 'BERETTA', 'MODEL 92', '9MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('HYKVWAHPIN', 'BERETTA', 'MODEL 92', '9MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('QH6BKJTM4L', 'BERETTA', 'MODEL 92', '9MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('NCYOUGXIVZ', 'FN HERSTAL', 'FIVE-SEVEN', '5.7x28MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('FR0XMXT3IT', 'FN HERSTAL', 'FIVE-SEVEN', '5.7x28MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('EMMXTER1T9', 'FN HERSTAL', 'FIVE-SEVEN', '5.7x28MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('UMTD6ZBIO4', 'FN HERSTAL', 'PS90', '5.7x28MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('EM49FK8J0J', 'FN HERSTAL', 'PS90', '5.7x28MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('XF6F9P9E5J', 'SIG SAUER', 'MPX', '9MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('SLN5AZ4WC9', 'SIG SAUER', 'MPX', '9MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('GW6DCU1J0X', 'SIG SAUER', 'MPX', '9MM', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('CGNRQDWDJW', 'SIG SAUER', 'P220', '.45 ACP', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('IONG10X9GP', 'SIG SAUER', 'P220', '.45 ACP', 'LOCKUP');
insert into system.guns (serial, manufacturer, model, caliber, location) values ('MHB4ZQRI8R', 'SIG SAUER', 'P220', '.45 ACP', 'LOCKUP');
